##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO TO CPANEL ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/cognitum/public_html/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH
